### ISSUE TITLE
include_docs => "true" gets encoded as include_docs=null in uri

### ISSUE THREAD

**Issue by flohoff** [norbu09/Store-CouchDB#12]
use strict;
use v5.14;      # switch aka given
use open IO => ":encoding(utf-8)";
use open ':std';
use Data::Dumper;

use Carp qw/croak/;
use Store::CouchDB;

my $sc = Store::CouchDB->new(
        debug => 1,
        user => 'flo',
        password => 'password',
        host => 'couchhost',
        ssl => 1,
        port => 443,
        db => 'couchdb/fidb');

my $array_ref = $sc->all_docs({ "include_docs" => "true" });

Running this with debugging returns:

Store::CouchDB: GET: https://rancid.filoo.de:443/couchdb/fidb/_all_docs?include_docs=null

Which obviously does not work. The couchdb returns 400 Bad Request.

This is Debian/Jessie 
flo@p3:~/projects/couchdb-perl/flo$ perl -v

This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi
(with 42 registered patches, see perl -V for more detail)

**Comment by norbu09** [comment]
Could you please run the tests and see if they run through for you?

https://github.com/norbu09/Store-CouchDB/blob/master/t/01-example.t

If not, please post the output here.
