### ISSUE TITLE
29 or 28 tests, that is the question

### ISSUE THREAD

**Issue by andk** [norbu09/Store-CouchDB#13]
Nearly all fail reports on cpantesters fail with 'planned to run 29 but done_testing() expects 28' on the test t/01-example.t. So I read the test just to find a cause for this failure and so far have only spotted one IF on the number of tests:

https://metacpan.org/source/NORBU/Store-CouchDB-3.8/t/01-example.t#L31
    $cleanup = 1 if $result->{ok} == 1;
https://metacpan.org/source/NORBU/Store-CouchDB-3.8/t/01-example.t#L270
if ($cleanup) {
        my $result = $sc->delete_db();
        ok($result->{ok} == 1, 'delete DB');
    }

So if cleanup is true, there will be one test more, otherwise one less. I tend to believe that the fixed counter 29 in line https://metacpan.org/source/NORBU/Store-CouchDB-3.8/t/01-example.t#L5 

For an overview of the failreports, see http://analysis.cpantesters.org/reports_by_field?distv=Store-CouchDB-3.8;field=qr%3A%23%20%28.%2B%20but%20done_testing.%2B%20expects%20.%2B%29

HTH&&Thanks,

**Comment by CodingMinds** [comment]
IIRC version 3.9 fixes this but is not yet released on CPAN.
@norbu09: Any plans to release v3.9 on CPAN ?

**Comment by nupfel** [comment]
this should be fixed with the release of 4.1
