### ISSUE TITLE
Warning about Any::Moose

### ISSUE THREAD

**Issue by kinginsun** [norbu09/Store-CouchDB#15]
Any::Moose is deprecated. Please use Moo instead at /Library/Perl/5.18/Store/CouchDB.pm line 3.

**Comment by dch** [comment]
@kinginsun thanks for the note. We see this here too and should roll a new release in the near future. In the meantime, please check your code works with a simple `s/use Any::Moose/use Moo/g` and report back. Thanks!

**Comment by dch** [comment]
BTW this was already addressed in 2e1a5ae36696e326fbcadb1f7025a6c481655a4e so you can try installing from git directly if that's easier.

**Comment by kinginsun** [comment]
Thanks for your kind reply.
