### ISSUE TITLE
Use of deprecated Any::Moose

### ISSUE THREAD

**Issue by karenetheridge** [norbu09/Store-CouchDB#6]
As documented, this is now deprecated in favour of Moo - see

http://shadow.cat/blog/matt-s-trout/moo-versus-any-moose/

for an explanation of why Any::Moose is broken by design.

**Comment by itcharlie** [comment]
Created this Pull request to resolve this issue : https://github.com/norbu09/Store-CouchDB/pull/9

**Comment by karenetheridge** [comment]
@itcharlie++

**Comment by nupfel** [comment]
thanks a lot eveyone
