### ISSUE TITLE
Missing del_file

### ISSUE THREAD

**Issue by a-maze-d** [norbu09/Store-CouchDB#7]
this client has support for adding (`put_file`) and getting (`get_file`) an attachment, but there is no way to delete (`del_file`) one (except of course it has an non-obvious name). Adding this functionality shouldn't be much effort (and I will do it myself if the functionality is not provided through this library), since it's for me a must have.

**Comment by norbu09** [comment]
Feel free to provide a pull request, we'll most likely just merge it in. The `file` commands were added by someone who needed them and we don't use them internally so never noticed that there was a missing `del_file`

**Comment by a-maze-d** [comment]
Sounds good :+1:
